import { StyleSheet, Text, View } from 'react-native';

import { Card, Metric, ProgressBar, Screen, ScreenHeader, SectionTitle } from '@/components/ui';
import { colors, spacing, typography } from '@/constants/theme';
import { useGymTrack } from '@/providers/GymTrackProvider';

const bars = [32, 54, 42, 76, 64, 92, 70];

export function ProgressScreen() {
  const { recentWorkouts, weeklyProgress } = useGymTrack();
  const percentage = weeklyProgress.target ? Math.min(100, Math.max(0, (weeklyProgress.completed / weeklyProgress.target) * 100)) : 0;
  return <Screen><ScreenHeader title="Progreso" subtitle="Historial local y métricas" /><View style={styles.metrics}><Card style={styles.metricCard}><Metric icon="checkmark-circle-outline" label="Esta semana · real" value={String(weeklyProgress.completed)} /></Card><Card style={styles.metricCard}><Metric icon="time-outline" label="Sesiones recientes · real" value={String(recentWorkouts.length)} /></Card></View><View style={styles.section}><SectionTitle detail="Datos locales">Entrenamientos recientes</SectionTitle>{recentWorkouts.length === 0 ? <Card><Text style={styles.emptyTitle}>Aún no hay sesiones completadas</Text><Text style={styles.emptyText}>Finaliza un entrenamiento y aparecerá aquí con su duración, ejercicios y series.</Text></Card> : <View style={styles.list}>{recentWorkouts.map((workout) => <Card key={workout.id} style={styles.historyCard}><View style={styles.historyCopy}><Text style={styles.historyTitle}>{workout.title}</Text><Text style={styles.historyDate}>{new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(workout.completedAt))}</Text></View><Text style={styles.historyMeta}>{workout.durationMinutes} min · {workout.exerciseCount} ejercicios · {workout.setCount} series</Text></Card>)}</View>}</View><View style={styles.section}><SectionTitle detail="DEMO · no calculado">Evolución</SectionTitle><Card><Text style={styles.demo}>Visual de referencia de Fase 1A</Text><View style={styles.chart}>{bars.map((height, index) => <View key={index} style={styles.barColumn}><View style={[styles.bar, { height }]} /><Text style={styles.barLabel}>{['L', 'M', 'X', 'J', 'V', 'S', 'D'][index]}</Text></View>)}</View></Card></View><View style={styles.section}><SectionTitle detail="DEMO">Récords personales</SectionTitle><Card style={styles.records}><Record exercise="Press banca" value="82,5 kg" /><Record exercise="Sentadilla" value="110 kg" /><Record exercise="Peso muerto" value="135 kg" /></Card></View><View style={styles.section}><SectionTitle detail={`${weeklyProgress.completed} de ${weeklyProgress.target} sesiones reales`}>Objetivo semanal</SectionTitle><Card style={styles.goal}><Text style={styles.goalValue}>{Math.round(percentage)}%</Text><ProgressBar value={percentage} /></Card></View></Screen>;
}

function Record({ exercise, value }: { exercise: string; value: string }) { return <View style={styles.record}><Text style={styles.exercise}>{exercise}</Text><Text style={styles.recordValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ metrics: { flexDirection: 'row', gap: spacing.md }, metricCard: { flex: 1, padding: spacing.lg }, section: { gap: spacing.md }, list: { gap: spacing.md }, emptyTitle: { ...typography.heading, color: colors.text }, emptyText: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm }, historyCard: { gap: spacing.sm }, historyCopy: { gap: spacing.xs }, historyTitle: { ...typography.heading, color: colors.text }, historyDate: { ...typography.caption, color: colors.textMuted }, historyMeta: { ...typography.caption, color: colors.primary }, demo: { ...typography.label, color: colors.warning }, chart: { height: 130, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: spacing.lg }, barColumn: { alignItems: 'center', gap: spacing.sm }, bar: { width: 16, borderRadius: 5, backgroundColor: colors.primary }, barLabel: { ...typography.label, color: colors.textMuted }, records: { paddingVertical: spacing.sm }, record: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, exercise: { ...typography.body, color: colors.text, fontWeight: '700', flex: 1 }, recordValue: { ...typography.heading, color: colors.text }, goal: { gap: spacing.lg }, goalValue: { ...typography.title, color: colors.primary } });
